import React, {useCallback} from 'react';

import {Container, Button, Row, Col, Card, Collapse, Form, Badge} from 'react-bootstrap';
import extract from './scripts/extract';
import { SayButton } from 'react-say';
import Say from 'react-say/lib/Say';
import logo from './logo.png';


import { fetchNewsCompletion, fetchDataCompletion } from './APIConnection';


class PreviousPod extends React.Component {


  constructor(props) {
    super(props);
  
    // Initializing the state 
    this.state = {
       
       insightsOpen: false,
       chatOpen: false,
       storyOpen: false,
       generateOpen: true,
       generateKeywordOpen: true,
       generateKeywordChatOpen: true,
       playKeywordStoryOpen: false,
       playKeywordChatOpen: false,
       playOpen: false,
       keywords: ['ChatGPT', 'AI', 'OpenAI'],
       transript_ar: "أهلا بكم في حلقة جديدة من برنامج إذاعي المملكة العربية السعودية للأخبار الاقتصادية.\
         في مستجدات الاقتصاد السعودي، شهدت السوق السعودية ارتفاعا ملحوظا خلال الأيام الماضية، حيث تجاوز المؤشر العام حاجز الـ 9000 نقطة، وذلك بفضل تحسّن الأداء الاقتصادي ورفع الحد الأدنى للأجور، بالإضافة إلى زيادة إيرادات النفط التي شهدتها المملكة.\
        في القطاع المصرفي، تمكنت بعض البنوك السعودية من تحقيق زيادة في أرباحها خلال الربع الثاني من العام الحالي، وذلك رغم تحديات عديدة مثل انخفاض الفائدة الصّافية وتراجع الأداء الاقتصادي لبعض الشركات.\
        وفي ما يتعلق بالأحداث العالمية، شهدت الأسواق العالمية توترا في الأسابيع الأخيرة بسبب التبادل الحاد للتهديدات بين الصين والولايات المتحدة، والتي قد تؤثر على اقتصادي العالم ككل إذا استمرّت هذه الحرب التجارية.\
        هذه كانت أبرز الأخبار الاقتصادية في هذا الأسبوع، نلتقي بكم في حلقة أخرى من برنامج إذاعي المملكة العربية السعودية للأخبار الاقتصادية. هذه الحلقة تم إعدادها باستخدام يوربود.",
       local: false,
       lang_ar: voices => [...voices].find(v => v.lang === 'ar-SA'), // 'ar-SA'
       transript_en: "Good morning and welcome to today's edition of the Saudi Arabian News. I'm your host and today's podcast will focus on news from the economy category in the kingdom.\
       First, in the oil and gas sector, the state-owned oil company Saudi Aramco announced that it has signed a Memorandum of Understanding with China's Zhejiang Free Trade Zone to develop a large petrochemical complex in China. The complex will have a processing capacity of 230,000 barrels a day and will be located in the Eastern province of Zhejiang. The agreement signifies a significant step in the relationship between Saudi Arabia and China as it will increase the kingdom's presence in the Chinese market.\
       Next, it was reported that Saudi Arabia's non-oil exports for the month of June 2021 increased by 102.9% compared to June 2020. The kingdom's exports for the month were valued at nearly SAR 20 billion, with China, the UAE, and Bahrain being the top export destinations.\
       In other news, the Saudi Arabian General Investment Authority (SAGIA) announced that the total number of foreign investor licenses issued in the second quarter of 2021 increased by 55% compared to the same period last year. The majority of the licenses were issued to investors from the United States, the United Kingdom, and the UAE.\
       Lastly, the Saudi Arabian Monetary Authority (SAMA) reported that the total net assets of Saudi banks increased by 17.9% in June 2021 compared to June 2020. The increase was attributed to the growth in the value of investments and bank credit facilities.\
       That's all for today's edition of the Saudi Arabian News focusing on the news from the economy category. Stay tuned for tomorrow's edition, and thank you for listening. This podcast was generated by your pod dot AI.",
        lang_en: voices => [...voices].find(v => v.lang === 'en-US'), // 'ar-SA'
       lang_s: 0,
       lang_s1:0,
       lang_s2: 0,
       cat : [],
      };
  }
  componentDidMount() {
   // extract()

 
  }

  render() {

    return(
    <Container fluid className="p-3  bg-dark">
      <Container className="p-5 mb-4 bg-dark rounded-3">

<img src={logo} className="App-logo" alt="logo" />
        <h1 className="header text-light" variant="light">UrPod.ai</h1>
        <br>

        </br>


        <Row>
          <Col>
        <Container>
      <Button
          aria-controls="example-collapse-text"
          aria-expanded='true'
          variant= "secondary" style={{ width: '25rem', height: '3rem', textAlign: 'left' }} text='white'
          className="text-left"
        >
          <i className="fas fa-lightbulb"></i>
            Previous Podcast  AR
        </Button>
        <Collapse in='true'>
        <Card bg='dark' key='dark' text='white'  className="mb-2">
        <Card.Header>Latest news  on 10 March 2023 </Card.Header>
        <Card.Body>
  
    
        <br>
        </br>

        <Collapse in='true'>
     <div>
      <SayButton
     onClick={ event => console.log(event) }
     voice={this.state.lang_ar}
     speak={this.state.transript_ar}
     pitch={ 1.1 }
     rate={ 0.9 }
     volume={ .8 }
     
   >
     Play Podcast
   </SayButton>
   </div>
   </Collapse>
        </Card.Body>
      </Card>
        </Collapse>

        
  
        </Container>
        </Col>



        <Col>
        <Container>
      <Button
          aria-controls="example-collapse-text"
          aria-expanded='true'
          variant= "secondary" style={{ width: '25rem', height: '3rem', textAlign: 'left' }} text='white'
          className="text-left"
        >
          <i className="fas fa-lightbulb"></i>
            Previous Podcast  EN
        </Button>
        <Collapse in='true'>
        <Card bg='dark' key='dark' text='white'  className="mb-2">
        <Card.Header>Latest news  on 10 March 2023 </Card.Header>
        <Card.Body>
  
    
        <br>
        </br>

        <Collapse in='true'>
     <div>
      <SayButton
     onClick={ event => console.log(event) }
     voice={this.state.lang_en}
     speak={this.state.transript_en}
     pitch={ 1.1 }
     rate={ 0.9 }
     volume={ .8 }
     
   >
     Play Podcast
   </SayButton>
   </div>
   </Collapse>
        </Card.Body>
      </Card>
        </Collapse>

        
  
        </Container>
        </Col>

        </Row>

  
  
  
      </Container>
    </Container>
  
  );
  
    }
  
}

export default PreviousPod;